# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a357c9094ef32be95e15b8d98252192317ddd9d5d998e9b22a95eee3b9035937d2b774d33b0d9e1faf7efb6c1262e79baff1091ec10b636ffd2a9cbcbb8f2009

test:
  secret_key_base: fedf28e48fee4a1dddb362e781215b801f0a2c26e74c0d347009098bb2e3bbce0db175e66df2cdc5421be406f480362637aff688a560e2baccf4c2bfce0b7646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
